from datetime import datetime, timedelta
import urllib.parse
from typing import Dict, Any, List
import logging

logger = logging.getLogger(__name__)

class CalendarService:
    @staticmethod
    def generate_google_calendar_link(task: Dict[str, Any], meeting_title: str) -> str:
        """Generate a Google Calendar event link for a task"""
        try:
            title = f"Task: {task.get('description', 'Action Item')}"
            
            # Format details
            details = f"Meeting: {meeting_title}\n"
            details += f"Priority: {task.get('priority', 'medium').upper()}\n"
            details += f"Owner: {task.get('owner', 'TBD')}\n\n"
            details += "Generated by MeetPulse AI"
            
            # Date handling
            deadline = task.get('deadline')
            if deadline:
                try:
                    # Expecting YYYY-MM-DD
                    dt = datetime.strptime(deadline, "%Y-%m-%d")
                except ValueError:
                    dt = datetime.now() + timedelta(days=1)
            else:
                dt = datetime.now() + timedelta(days=1)
                
            # Google dates format: YYYYMMDDTHHMMSSZ
            start_time = dt.strftime("%Y%m%dT090000Z")
            end_time = dt.strftime("%Y%m%dT100000Z")
            
            params = {
                'action': 'TEMPLATE',
                'text': title,
                'details': details,
                'dates': f"{start_time}/{end_time}"
            }
            
            return f"https://www.google.com/calendar/render?{urllib.parse.urlencode(params)}"
        except Exception as e:
            logger.error(f"Error generating Google Calendar link: {str(e)}")
            return ""

    @staticmethod
    def generate_outlook_calendar_link(task: Dict[str, Any], meeting_title: str) -> str:
        """Generate an Outlook Calendar event link for a task"""
        try:
            subject = f"Task: {task.get('description', 'Action Item')}"
            
            # Format body
            body = f"Meeting: {meeting_title}\n"
            body += f"Priority: {task.get('priority', 'medium').upper()}\n"
            body += f"Owner: {task.get('owner', 'TBD')}\n\n"
            body += "Generated by MeetPulse AI"
            
            # Date handling
            deadline = task.get('deadline')
            if deadline:
                try:
                    dt = datetime.strptime(deadline, "%Y-%m-%d")
                except ValueError:
                    dt = datetime.now() + timedelta(days=1)
            else:
                dt = datetime.now() + timedelta(days=1)

            start_dt = dt.strftime("%Y-%m-%dT09:00:00")
            end_dt = dt.strftime("%Y-%m-%dT10:00:00")
            
            params = {
                'path': '/calendar/action/compose',
                'rru': 'addevent',
                'subject': subject,
                'body': body,
                'startdt': start_dt,
                'enddt': end_dt
            }
            
            return f"https://outlook.live.com/calendar/0/deeplink/compose?{urllib.parse.urlencode(params)}"
        except Exception as e:
            logger.error(f"Error generating Outlook Calendar link: {str(e)}")
            return ""

    @staticmethod
    def generate_ics_content(tasks: List[Dict[str, Any]], meeting_title: str) -> str:
        """Generate iCalendar (.ics) content for multiple tasks"""
        ics_lines = [
            "BEGIN:VCALENDAR",
            "VERSION:2.0",
            "PRODID:-//MeetPulse//AI Meeting Notes//EN",
            "CALSCALE:GREGORIAN",
            "METHOD:PUBLISH"
        ]
        
        for task in tasks:
            dt_stamp = datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
            
            deadline = task.get('deadline')
            if deadline:
                try:
                    dt = datetime.strptime(deadline, "%Y-%m-%d")
                except ValueError:
                    dt = datetime.now() + timedelta(days=1)
            else:
                dt = datetime.now() + timedelta(days=1)
                
            start_time = dt.strftime("%Y%m%dT090000Z")
            end_time = dt.strftime("%Y%m%dT100000Z")
            
            summary = f"Task: {task.get('description', 'Action Item')}"
            description = f"Meeting: {meeting_title}\\nPriority: {task.get('priority', 'medium').upper()}\\nOwner: {task.get('owner', 'TBD')}"
            
            ics_lines.extend([
                "BEGIN:VEVENT",
                f"DTSTAMP:{dt_stamp}",
                f"DTSTART:{start_time}",
                f"DTEND:{end_time}",
                f"SUMMARY:{summary}",
                f"DESCRIPTION:{description}",
                f"UID:{task.get('id', datetime.now().timestamp())}@meetpulse.ai",
                "END:VEVENT"
            ])
            
        ics_lines.append("END:VCALENDAR")
        return "\n".join(ics_lines)
