import httpx
import logging
from typing import Optional, Dict, Any, List
from app.core.config import settings

logger = logging.getLogger(__name__)

class TrelloService:
    """Service for exporting meeting tasks (action items) to Trello"""
    
    def __init__(self):
        self.api_key = settings.TRELLO_API_KEY
        self.token = settings.TRELLO_TOKEN
        self.list_id = settings.TRELLO_LIST_ID # User should provide a list ID where tasks go
        self.api_url = 'https://api.trello.com/1'
        
    async def export_tasks(self, transcript_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Export action items from meeting transcript to Trello as cards.
        
        Args:
            transcript_data: Meeting transcript with action items
            
        Returns:
            Status summary of the export
        """
        if not self.api_key or not self.token or not self.list_id:
            logger.warning("Trello API credentials or List ID missing")
            return {
                'success': False, 
                'error': 'Trello configuration missing. Please add TRELLO_API_KEY, TRELLO_TOKEN, and TRELLO_LIST_ID to .env'
            }
        
        action_items = transcript_data.get('actionItems', [])
        if not action_items:
            return {'success': True, 'message': 'No action items to export', 'cards_created': 0}
        
        results = []
        try:
            async with httpx.AsyncClient() as client:
                for item in action_items:
                    card_data = self._prepare_card_data(item, transcript_data.get('title', 'Meeting'))
                    
                    params = {
                        'key': self.api_key,
                        'token': self.token,
                        **card_data
                    }
                    
                    response = await client.post(
                        f'{self.api_url}/cards',
                        params=params
                    )
                    
                    if response.status_code == 200:
                        results.append({'id': response.json().get('id'), 'success': True})
                    else:
                        logger.error(f"Failed to create Trello card: {response.text}")
                        results.append({'success': False, 'error': response.text})
            
            success_count = sum(1 for r in results if r.get('success'))
            return {
                'success': success_count > 0,
                'cards_created': success_count,
                'total_tasks': len(action_items),
                'details': results
            }
            
        except Exception as e:
            logger.error(f"Error exporting to Trello: {str(e)}")
            return {'success': False, 'error': str(e)}
            
    def _prepare_card_data(self, item: Dict[str, Any], meeting_title: str) -> Dict[str, Any]:
        """Prepare card data for Trello API"""
        description = item.get('description', 'No description')
        owner = item.get('owner', 'Unassigned')
        priority = item.get('priority', 'Medium').upper()
        deadline = item.get('deadline', 'No deadline')
        
        card_name = f"[{priority}] {description}"
        card_desc = f"Source Meeting: {meeting_title}\nOwner: {owner}\nDeadline: {deadline}\n\nGenerated by MeetPulse AI"
        
        return {
            'name': card_name,
            'desc': card_desc,
            'idList': self.list_id,
            'pos': 'top'
        }
