import { ActionItem } from '@/types';

export const generateGoogleCalendarLink = (task: ActionItem, meetingTitle: string): string => {
    const title = `Task: ${task.description}`;
    const details = `Meeting: ${meetingTitle}\nPriority: ${task.priority.toUpperCase()}\nOwner: ${task.owner || 'TBD'}\n\nGenerated by MeetPulse AI`;

    let startDate = new Date();
    if (task.deadline) {
        const d = new Date(task.deadline);
        if (!isNaN(d.getTime())) {
            if (d.getFullYear() === 2001) {
                d.setFullYear(new Date().getFullYear());
            }
            startDate = d;
        } else {
            startDate.setDate(startDate.getDate() + 1);
        }
    } else {
        startDate.setDate(startDate.getDate() + 1);
    }

    // Set to 9 AM
    startDate.setHours(9, 0, 0, 0);
    const endDate = new Date(startDate);
    endDate.setHours(10, 0, 0, 0);

    const formatDate = (date: Date) => date.toISOString().replace(/-|:|\.\d+/g, '');

    const params = new URLSearchParams({
        action: 'TEMPLATE',
        text: title,
        details: details,
        dates: `${formatDate(startDate)}/${formatDate(endDate)}`,
    });

    return `https://www.google.com/calendar/render?${params.toString()}`;
};

export const generateOutlookCalendarLink = (task: ActionItem, meetingTitle: string): string => {
    const subject = `Task: ${task.description}`;
    const body = `Meeting: ${meetingTitle}\nPriority: ${task.priority.toUpperCase()}\nOwner: ${task.owner || 'TBD'}\n\nGenerated by MeetPulse AI`;

    let startDate = new Date();
    if (task.deadline) {
        const d = new Date(task.deadline);
        if (!isNaN(d.getTime())) {
            startDate = d;
        } else {
            startDate.setDate(startDate.getDate() + 1);
        }
    } else {
        startDate.setDate(startDate.getDate() + 1);
    }

    startDate.setHours(9, 0, 0, 0);
    const endDate = new Date(startDate);
    endDate.setHours(10, 0, 0, 0);

    const formatDate = (date: Date) => date.toISOString().split('.')[0] + 'Z';

    const params = new URLSearchParams({
        path: '/calendar/action/compose',
        rru: 'addevent',
        subject: subject,
        body: body,
        startdt: startDate.toISOString(),
        enddt: endDate.toISOString(),
    });

    return `https://outlook.live.com/calendar/0/deeplink/compose?${params.toString()}`;
};

export const generateICSContent = (tasks: ActionItem[], meetingTitle: string): string => {
    let ics = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        'PRODID:-//MeetPulse//AI Meeting Notes//EN',
        'CALSCALE:GREGORIAN',
        'METHOD:PUBLISH',
    ];

    const formatDate = (date: Date) => date.toISOString().replace(/-|:|\.\d+/g, '');

    tasks.forEach((task) => {
        let startDate = new Date();
        if (task.deadline) {
            const d = new Date(task.deadline);
            if (!isNaN(d.getTime())) {
                startDate = d;
            } else {
                startDate.setDate(startDate.getDate() + 1);
            }
        } else {
            startDate.setDate(startDate.getDate() + 1);
        }

        startDate.setHours(9, 0, 0, 0);
        const endDate = new Date(startDate);
        endDate.setHours(10, 0, 0, 0);

        const now = new Date();

        ics.push('BEGIN:VEVENT');
        ics.push(`DTSTAMP:${formatDate(now)}`);
        ics.push(`DTSTART:${formatDate(startDate)}`);
        ics.push(`DTEND:${formatDate(endDate)}`);
        ics.push(`SUMMARY:Task: ${task.description}`);
        ics.push(`DESCRIPTION:Meeting: ${meetingTitle}\\nPriority: ${task.priority.toUpperCase()}\\nOwner: ${task.owner || 'TBD'}`);
        ics.push(`UID:${task.id}@meetpulse.ai`);
        ics.push('END:VEVENT');
    });

    ics.push('END:VCALENDAR');
    return ics.join('\r\n');
};
